version: '3.8'
services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-docker
    stdin_open: true
    volumes:
        - './:/app'
        - '/app/node_modules'
    environment:
        - CHOKIDAR_USEPOLLING=true